# Generated by Django 4.2.7 on 2025-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Ключ сессии/токена"
            ),
        ),
    ]
