# Используем базовый образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт для Vite Dev Server
EXPOSE 5173

# Команда для запуска Vite Dev Server
CMD ["npm", "run", "dev", "--", "--host"]