# Generated by Django 5.1.5 on 2025-01-22 17:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('IP', 'Индивидуальный предприниматель'), ('LEGAL', 'Юридическое лицо')], default='LEGAL', max_length=10, verbose_name='Вид клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('fact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счёт')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК Банка')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование Банка')),
                ('director_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Директора')),
                ('director_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность Директора')),
                ('director_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание')),
                ('signatory_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО подписанта')),
                ('signatory_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность подписанта')),
                ('signatory_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание подписанта')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо компании')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя контактного лица')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientgroup', verbose_name='Группа')),
                ('tags', models.ManyToManyField(blank=True, to='clients.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('IP', 'Индивидуальный предприниматель'), ('LEGAL', 'Юридическое лицо')], default='LEGAL', max_length=10, verbose_name='Вид клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('fact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счёт')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК Банка')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование Банка')),
                ('director_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Директора')),
                ('director_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность Директора')),
                ('director_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание')),
                ('signatory_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО подписанта')),
                ('signatory_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность подписанта')),
                ('signatory_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание подписанта')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо компании')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя контактного лица')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контактного лица')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.clientgroup', verbose_name='Группа')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Клиент',
                'verbose_name_plural': 'historical Клиенты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('BRANCH', 'Филиал'), ('PARTNER', 'Партнёр'), ('PARENT', 'Головная компания')], max_length=10)),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='clients.client')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='clients.client')),
            ],
            options={
                'verbose_name': 'Связь клиентов',
                'verbose_name_plural': 'Связи клиентов',
                'indexes': [models.Index(fields=['from_client', 'to_client'], name='clients_cli_from_cl_bd0ba0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Звонок'), ('MEETING', 'Встреча'), ('EMAIL', 'Письмо')], max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'indexes': [models.Index(fields=['client', 'date'], name='clients_int_client__8f716a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='client_search_vector_idx'),
        ),
    ]
