# Generated by Django 5.1.5 on 2025-01-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер договора')),
                ('name', models.CharField(max_length=255, verbose_name='Имя договора')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата договора')),
                ('status', models.CharField(choices=[('Подписан', 'Подписан'), ('Не подписан', 'Не подписан'), ('На согласовании', 'На согласовании')], max_length=50, verbose_name='Статус')),
                ('igk_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ИГК')),
                ('file', models.FileField(upload_to='docs/%Y/%m/%d/', verbose_name='Файл договора')),
                ('change_history', models.JSONField(blank=True, null=True, verbose_name='История изменений')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер спецификации')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата спецификации')),
                ('igk_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ИГК')),
                ('goods_services', models.TextField(verbose_name='Товары/Услуги')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('file', models.FileField(upload_to='docs/%Y/%m/%d/', verbose_name='Файл спецификации')),
                ('change_history', models.JSONField(blank=True, null=True, verbose_name='История изменений')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('date', models.DateField(verbose_name='Дата счета')),
                ('status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Оплачен частично', 'Оплачен частично'), ('Не оплачен', 'Не оплачен'), ('Отменен', 'Отменен')], max_length=50, verbose_name='Статус')),
                ('payment_due_date', models.DateField(verbose_name='Срок оплаты')),
                ('goods_services', models.TextField(verbose_name='Товары/Услуги')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('file', models.FileField(upload_to='docs/%Y/%m/%d/', verbose_name='Файл счета')),
                ('change_history', models.JSONField(blank=True, null=True, verbose_name='История изменений')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.contract', verbose_name='Договор')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.specification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счета на оплату',
            },
        ),
        migrations.CreateModel(
            name='UPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер УПД')),
                ('date', models.DateField(verbose_name='Дата УПД')),
                ('status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Оплачен частично', 'Оплачен частично'), ('Не оплачен', 'Не оплачен')], max_length=50, verbose_name='Статус')),
                ('igk_number', models.CharField(blank=True, max_length=50, verbose_name='Номер ИГК')),
                ('goods_services', models.TextField(verbose_name='Товары/Услуги')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('signing_status', models.CharField(choices=[('Подписана по ЭДО', 'Подписана по ЭДО'), ('Подписан в оригинале', 'Подписан в оригинале'), ('Не подписан', 'Не подписан')], max_length=50, verbose_name='Статус подписания')),
                ('file', models.FileField(upload_to='docs/%Y/%m/%d/', verbose_name='Файл УПД')),
                ('change_history', models.JSONField(blank=True, null=True, verbose_name='История изменений')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.contract', verbose_name='Договор')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.invoice', verbose_name='Счет на оплату')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.specification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'УПД',
                'verbose_name_plural': 'УПД',
            },
        ),
    ]
