# Generated by Django 5.1.5 on 2025-01-30 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_contract_file_alter_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата спецификации'),
        ),
    ]
