# Generated by Django 5.1.5 on 2025-02-25 08:21

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_contract_date_alter_specification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='goods_services',
            field=models.TextField(blank=True, verbose_name='Товары/Услуги'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, verbose_name='Срок оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.get_specification_upload_path, verbose_name='Файл спецификации'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='goods_services',
            field=models.TextField(blank=True, verbose_name='Товары/Услуги'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='upd',
            name='goods_services',
            field=models.TextField(blank=True, verbose_name='Товары/Услуги'),
        ),
        migrations.AlterField(
            model_name='upd',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
