# Generated by Django 4.2.7 on 2025-03-03 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(100),
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(100),
                ],
                verbose_name="Название",
            ),
        ),
    ]
